default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tusk_development

test:
  <<: *default
  database: tusk_test

production:
  <<: *default
  database: tusk_production
  username: tusk
  password: <%= ENV["TUSK_DATABASE_PASSWORD"] %>
